# -*- coding: utf-8 -*-

"""
    calculatorapi

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""

from calculatorapi.decorators import lazy_property
from calculatorapi.configuration import Configuration
from calculatorapi.controllers.simple_calculator_controller import SimpleCalculatorController


class CalculatorapiClient(object):

    config = Configuration

    @lazy_property
    def simple_calculator(self):
        return SimpleCalculatorController()


