# -*- coding: utf-8 -*-

"""
    calculatorapi

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""

class OperationTypeEnum(object):

    """Implementation of the 'Operation Type' enum.

    Possible Operations are sum, subtract, multiply and divide

    Attributes:
        ADD: This operation will add the operands
        SUBTRACT: This operation will subtract the operands
        MULTIPLY: This operation will multiply the operands
        DIVIDE: This operation will divide the operands

    """

    ADD = 'SUM'

    SUBTRACT = 'SUBTRACT'

    MULTIPLY = 'MULTIPLY'

    DIVIDE = 'DIVIDE'

